settings:
  files:
    outputs:
      status: true
      path: ""
      name: .r.outputs.log
    logs:
      status: true
      path: ""
      name: .r.logs.log
    errors:
      status: true
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
schema:
- name: mobile-developer-console
  path: .
  env:
  commands:
    build:
      status: true
      args:
      - -o mobile-developer-console
      - ./cmd/api-server/main.go
  watcher:
    extensions:
    - go
    paths:
    - .
    ignored_paths:
    - .git
    - .realize
    - vendor
    - ui
    scripts:
    - type: before
      command: ./scripts/development.sh kill-go-server
      global: false
    - type: after
      command: echo "Running server on port 4000"
      global: false
    - type: after
      command: ./scripts/development.sh go-server
      global: false
